### ISSUE TITLE
Deploy demo to gh-pages using angular-deploy-gh-pages-actions

### ISSUE THREAD

**Issue by AhsanAyaz** [AhsanAyaz/ngx-read-time#7]
We have a demo already in this workspace. What we need to do is deploy the demo to GitHub Pages so it is viewable by others.
For that, I already created a GitHub Action named angular-deploy-gh-pages-actions. Documentation here:
https://github.com/AhsanAyaz/angular-deploy-gh-pages-actions

Example workflow file:
https://github.com/AhsanAyaz/angular-deploy-gh-pages-actions/blob/master/.github/workflows/test.yml

**Comment by mehdirajani5** [comment]
I am working on it.
